---
title: "BigHornSheep, 2009    "
author: "Ryker Brian"
date: '2022-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Upload

### Libraries

```{r include=FALSE}
library(tidyr)
library(tidyverse)
library(stringr)
library(mapview)
library(sf)
library(sp)

library(rgeos)
```

copy coordinates from pdf and save as .txt file. Delete all line breaks before uploading using find/replace function

```{r}
txt1_2009 <- t(
  read.csv("/Users/ryker/Critical Habitats Project/BHS 2009 /Unit1_2009.txt", header = FALSE, sep = ";")) # transposed to long
txt1_2009_df <- as.data.frame(txt1_2009) # convert to df
txt1_2009_df$Unit <- "1" # add area unit


txt2_2009 <- t(
  read.csv("/Users/ryker/Critical Habitats Project/BHS 2009 /Unit2A_2009.txt", header = FALSE, sep = ";"))
txt2_2009_df <- as.data.frame(txt2_2009) 
txt2_2009_df$Unit <- "2"

txt3_2009 <- t(
  read.csv("/Users/ryker/Critical Habitats Project/BHS 2009 /Unit2B_2009.txt", header = FALSE, sep = ";"))
txt3_2009_df <- as.data.frame(txt3_2009) 
txt3_2009_df$Unit <- "3"

txt4_2009 <- t(
  read.csv("/Users/ryker/Critical Habitats Project/BHS 2009 /Unit3_2009.txt", header = FALSE, sep = ";"))
txt4_2009_df <- as.data.frame(txt4_2009) 
txt4_2009_df$Unit <- "4"
```


Combine into one dataset
```{r}
cord_df <- rbind(txt1_2009_df, txt2_2009_df) %>%
  rbind(txt3_2009_df) %>%
  rbind(txt4_2009_df) 

```


Reformat data frame

```{r}

rownames(cord_df) <- NULL # delete row names

colnames(cord_df) <- c("Coordinates", "Unit") # add name columns

cord_df <- cord_df %>% na.omit # delete empty rows


cord_df
```
## Create Shape Files

separate coordinates into latitude and longitude columns 

```{r}
cord_df <- separate(cord_df, "Coordinates", c("lat", "lon"), ",")

# convert from factor to numeric
cord_df$lat <- as.numeric(cord_df$lat)
cord_df$lon <- as.numeric(cord_df$lon)
cord_df$Unit <- as.numeric(cord_df$Unit)

cord_df
```

Crs gathered based on GeodeticaDA and utmZone
https://spatialreference.org/ref/epsg/nad83-utm-zone-11n/ 




## Create Spacial file 

```{r}

# make a list
cord_list <- split(cord_df, cord_df$Unit)

# extract lon-lats in the list, not the names
cord_list <- lapply(cord_list, function(x) { x["Unit"] <- NULL; x })


# create SpatialPolygons Object, convert coords to polygon
ps <- lapply(cord_list, Polygon)


# add Unit variable
p1 <- lapply(seq_along(ps), function(i) Polygons(list(ps[[i]]), 
                                            ID = names(cord_list)[i]  ))

# create spatial polygons
bhs_sp <- SpatialPolygons(p1, proj4string = CRS("+proj=utm +zone=11 +ellps=GRS80 +datum=NAD83 +units=m +no_defs") )


# create spatial polygon df
bhs_spdf <- SpatialPolygonsDataFrame(bhs_sp, 
 data.frame(Unit = unique(cord_df$Unit), 
            row.names = unique(cord_df$Unit)))

# convert to shapefile
bhs_sf <- st_as_sf(bhs_spdf, crs = "+proj=utm +zone=11 +ellps=GRS80 +datum=NAD83 +units=m +no_defs ")
```


```{r}
"Bighorn Sheep Habitat 2009" <- bhs_sf # rename for legend title

mapview(`Bighorn Sheep Habitat 2009`)
```